# Generated by Django 3.1 on 2020-09-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_email', models.CharField(max_length=30)),
                ('member_pwd', models.CharField(max_length=20)),
                ('member_nick', models.CharField(max_length=15)),
                ('member_op', models.BooleanField(default=False)),
                ('member_ban', models.BooleanField(default=False)),
            ],
        ),
    ]
