# Generated by Django 3.1.1 on 2020-09-15 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('mood_id', models.AutoField(primary_key=True, serialize=False)),
                ('mood_val', models.CharField(max_length=10)),
                ('mood_state', models.CharField(max_length=50)),
                ('mood_content', models.TextField()),
                ('mood_date', models.DateTimeField(auto_now=True)),
                ('mood_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
