# Generated by Django 3.1 on 2020-09-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prefer',
            name='prefer_member_id',
        ),
        migrations.RemoveField(
            model_name='prefer',
            name='prefer_topic',
        ),
    ]
